In [1]:
import numpy as np 

In [2]:
n = np.array([[1,2],[3,2]])

In [3]:
n.shape

(2, 2)

In [4]:
n.dtype

dtype('int64')

In [5]:
#inceerting 5 to poistion (0,0)
n[0,0] = 5 

In [6]:
n

array([[5, 2],
       [3, 2]])

In [17]:
#np.start(start,stop,steps)
# here stop = stop - 1 
np.arange(0,21,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [19]:
#np.linspace(start,stop,number_of_elemets)
#stop and start are both included 
np.linspace(0,20,12)

array([ 0.        ,  1.81818182,  3.63636364,  5.45454545,  7.27272727,
        9.09090909, 10.90909091, 12.72727273, 14.54545455, 16.36363636,
       18.18181818, 20.        ])

In [21]:
#creating the random matrix
#     np.random.rand(row,column) `
mat = np.random.rand(5,5)
mat

array([[0.88007851, 0.99955715, 0.06061169, 0.25644583, 0.16704028],
       [0.93516465, 0.96893481, 0.28553294, 0.5286615 , 0.23264854],
       [0.58433449, 0.76774789, 0.1294152 , 0.84999143, 0.43127432],
       [0.81673564, 0.34792519, 0.6837824 , 0.65182822, 0.94815862],
       [0.22257626, 0.65694756, 0.35000949, 0.95151186, 0.96351408]])

In [22]:
#seeing only first 3 rows 
mat[:3,:]

array([[0.88007851, 0.99955715, 0.06061169, 0.25644583, 0.16704028],
       [0.93516465, 0.96893481, 0.28553294, 0.5286615 , 0.23264854],
       [0.58433449, 0.76774789, 0.1294152 , 0.84999143, 0.43127432]])